CREATE TABLE IF NOT EXISTS posts
(
    id             BIGINT PRIMARY KEY,
    title          VARCHAR(100) NOT NULL,
    text           VARCHAR(250) NOT NULL,
    likes_count    INTEGER      NOT NULL
);

CREATE TABLE IF NOT EXISTS comments
(
    id      BIGINT PRIMARY KEY,
    text    varchar(250) NOT NULL,
    post_id bigint references posts (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS post_tags
(
    record_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id   BIGINT references posts (id) ON DELETE CASCADE ,
    tag       varchar(20)
);

CREATE TABLE IF NOT EXISTS post_image
(
    post_id      BIGINT PRIMARY KEY REFERENCES posts (id) ON DELETE CASCADE,
    file_name    VARCHAR(255) NOT NULL,
    content_type VARCHAR(100),
    file_size    BIGINT       NOT NULL,
    file_data    BYTEA        NOT NULL
);

